name: Mera Phela CI/CD Workflow

on:
  push:
     branches: [ main ]



jobs:
   python-test-job:
     runs-on: ubuntu-latest
     steps:
         - name: Code Copy Karo
           uses: actions/checkout@v4

         - name: Python Setup Karo
           uses: actions/setup-python@v5
           with:
               python-version: '3.10'


         - name: Mera Python Code Run Karo
           run: python app.py
